# Generated by Django 4.0.3 on 2022-04-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
